---

- name: Set up debian machine
  hosts: all
  become: true
  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add sudoers users to wheel group
      user:
        name: debian
        groups: wheel
        append: yes
        state: present
        createhome: yes
        shell: /bin/bash

    - name: Fetch packages
      block:
        - name: Update sources
          apt:
            upgrade: dist
            update_cache: yes

        - name: Install packages
          apt:
            pkg:
              - jq
              - git
              - gcc
              - vim
              - curl
              - make
              - tmux
              - wget
              - rsync
              - unzip
              - auditd
              - firewalld
            state: latest
